spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/serverdb
  jpa:
    hibernate:
      ddl_auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
    show_sql: true
